export const LOGIN_ROUTE = '/login'
export const PRODUCT_LIST = '/product'
export const PRODUCT_INFO = '/product/info'
export const PRODUCT_ADD = '/product/add'
export const PRODUCT_EDIT = '/product/edit'